/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/block/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#1A1A1A",
        "input-bg": "#f9fafb",
        "dark-input-bg": "#232426",
        "input-border": "#E5E6EB",
        "dark-input-border": "#2D2D2D",
        "light": "#9CA3AF",
        "white": "#ffffff",
        "success-primary": "#046C4E",
        "success-primary-light": "#DEF7EC",
        "warning-primary": "#9B1C1C",
        "warning-primary-light": "#FDE8E8",
        "red-bg": "#FDE8E8",
        "red-text": "#9B1C1C",
        "blue-bg": "#E8EDFF",
        "blue-text": "#184BFE",
        "green-bg": "#DEF7EC",
        "green-text": "#046C4E",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        md: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "36px",
      },
      screens: {
        xs: "430px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1440px",
        "3xl": "1920px",
      },
      spacing: {
        2: "2px",
        4: "4px",
        6: "6px",
        8: "8px",
        12: "12px",
        16: "16px",
        24: "24px",
        32: "32px",
        40: "40px",
        48: "48px",
        56: "56px",
        64: "64px",
        72: "72px",
        80: "80px",
        96: "96px",
        128: "128px",
        144: "144px",
        160: "160px",
        176: "176px",
      },
      borderRadius: {
        main: "10px",
      },
    },
  },
  plugins: [],
  darkMode: "class",
};
