"use client";
import "./globals.css";
import { usePathname } from "next/navigation";
import { ReduxProvider } from "@/redux/provider";
import { ThemeProvider } from "next-themes";
import dynamic from "next/dynamic";
import Skeleton from "@/ui/block/Sekeleton/Skeleton";
const Bg = dynamic(() => import("@/ui/layout/Bg/Bg"), {
  loading: () => <Skeleton className="w-full h-full" />,
  ssr: false,
});

const metadata = {
  title: "Focus Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showBg = pathname.includes("login") || pathname.includes("register");

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link rel="icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <ReduxProvider>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            storageKey="theme"
          >
            {showBg && <Bg />}
            {children}
          </ThemeProvider>
        </body>
      </ReduxProvider>
    </html>
  );
}
