"use client";
import Bg from "@/ui/layout/Bg/Bg";
import "./globals.css";
import { usePathname } from "next/navigation";
import { ReduxProvider } from "@/redux/provider";

const metadata = {
  title: "Focus Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showBg = pathname.includes("login") || pathname.includes("register");

  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link rel="icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <ReduxProvider>
        <body className="" suppressHydrationWarning={true}>
          {showBg && <Bg />}
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
